# Generated by Django 3.1.3 on 2020-11-16 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfileInfo',
            fields=[
                ('worker_number', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('gate_worker', models.BooleanField(blank=True, default=False)),
                ('city_address', models.CharField(blank=True, max_length=256)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('date', models.DateField(default=None, primary_key=True, serialize=False)),
                ('shift_time', models.CharField(default=None, max_length=256)),
                ('capacity', models.PositiveIntegerField(default=5)),
                ('value', models.PositiveIntegerField(default=0)),
                ('creation_time', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='worker_shift', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
